# Generated by Django 5.2.10 on 2026-02-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_userprofile_image_alter_userprofile_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IshHaqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel_raqam', models.CharField(max_length=20, unique=True, verbose_name='Tabel Raqami')),
                ('norma_ish', models.FloatField(default=0.0, verbose_name='Norma ish soati')),
                ('oklad', models.FloatField(verbose_name="Oylik oklad (so'm)")),
                ('tungi_soat', models.FloatField(default=0.0, verbose_name='Tungi soatlar')),
                ('bayram_soat', models.FloatField(default=0.0, verbose_name='Bayram soatlari')),
                ('ishlangan_soat', models.FloatField(verbose_name='Haqiqiy ishlangan soat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
        ),
    ]
