# Generated by Django 5.2.10 on 2026-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_ishhaqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishhaqi',
            name='tabel_raqam',
            field=models.CharField(max_length=20, verbose_name='Tabel Raqami'),
        ),
    ]
