# Generated by Django 5.2.10 on 2026-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_ishhaqi_tabel_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishhaqi',
            name='bayram_soat',
            field=models.FloatField(verbose_name='Bayram soatlari'),
        ),
        migrations.AlterField(
            model_name='ishhaqi',
            name='norma_ish',
            field=models.FloatField(verbose_name='Norma ish soati'),
        ),
        migrations.AlterField(
            model_name='ishhaqi',
            name='tungi_soat',
            field=models.FloatField(verbose_name='Tungi soatlar'),
        ),
    ]
